(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/registration (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/registration (master)
$ cd ..
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL (master)
$ ls
 blogs/               'more practice'/      Normalization/   twitter/           World/
'Cities and States'/   myBooks/             registration/   'User Dashboard'/
 Friendships/          mysqlconnection.py   sakila/          users/
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL (master)
$ cd users
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ ls
css/  img/  js/  mysqlconnection.py  server.py  static/  templates/  users.mwb
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.sysconfig import get_python_lib
>>> print get_python_lib
<function sysconfig_get_python_lib at 0x00000000036B5B38>
>>> print get_python_lib()
C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\Lib\site-packages
>>> ls -l C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\Lib\site-packages
  File "<stdin>", line 1
    ls -l C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\Lib\site-packages
          ^
SyntaxError: invalid syntax
>>> ls -l
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ls' is not defined
>>> ls -l \Users\
  File "<stdin>", line 1
    ls -l \Users\
                ^
SyntaxError: unexpected character after line continuation character
>>> ls -l \Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\Lib\site-packages | gr
ep -i mysql

Traceback (most recent call last):
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\encodings\cp437.py
", line 14, in decode
    def decode(self,input,errors='strict'):
KeyboardInterrupt
>>> import mysql.connector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mysql.connector
>>> exit()
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
click (6.7)
Flask (0.12.1)
Flask-SQLAlchemy (2.2)
itsdangerous (0.24)
Jinja2 (2.9.6)
MarkupSafe (1.0)
mysqlclient (1.3.10)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
setuptools (35.0.1)
six (1.10.0)
SQLAlchemy (1.1.9)
Werkzeug (0.12.1)
wheel (0.29.0)
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from MySQLConnection import MySQLConnector
ImportError: No module named MySQLConnection
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    print mysql.query_db('SELECT * FROM users.users')
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\SQL\users\mysqlconnection.py", line 21, in que
ry_db
    result = self.db.session.execute(text(query), data)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1135, in _do_get
    return self._create_connection()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'user
s.db'")
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    print mysql.query_db('SELECT * FROM usersdb.users')
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\SQL\users\mysqlconnection.py", line 21, in que
ry_db
    result = self.db.session.execute(text(query), data)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1135, in _do_get
    return self._create_connection()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'user
sdb.db'")
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
[]
 * Restarting with stat
[]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:8888/ (Press CTRL+C to quit)
 * Detected change in 'C:\\Users\\Mikus\\desktop\\DojoAssignments\\Python\\SQL\\users\\server.py', r
eloading
 * Restarting with stat
[]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:3306/ (Press CTRL+C to quit)
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
[]
 * Restarting with stat
[]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:3306/ (Press CTRL+C to quit)
 * Detected change in 'C:\\Users\\Mikus\\desktop\\DojoAssignments\\Python\\SQL\\users\\server.py', r
eloading
 * Restarting with stat
[{u'first_name': u'Michael', u'last_name': u'Benson', u'created_at': datetime.datetime(2017, 4, 20,
16, 43, 12), u'updated_at': datetime.datetime(2017, 4, 20, 16, 43, 12), u'email': u'freefaller@gmail
.com', u'id': 1L}]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:3306/ (Press CTRL+C to quit)
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
[{u'first_name': u'Michael', u'last_name': u'Benson', u'created_at': datetime.datetime(2017, 4, 20,
16, 43, 12), u'updated_at': datetime.datetime(2017, 4, 20, 16, 43, 12), u'email': u'freefaller@gmail
.com', u'id': 1L}]
 * Restarting with stat
[{u'first_name': u'Michael', u'last_name': u'Benson', u'created_at': datetime.datetime(2017, 4, 20,
16, 43, 12), u'updated_at': datetime.datetime(2017, 4, 20, 16, 43, 12), u'email': u'freefaller@gmail
.com', u'id': 1L}]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:3306/ (Press CTRL+C to quit)
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    print mysql.query_db('SELECT * FROM users')
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\SQL\users\mysqlconnection.py", line 21, in que
ry_db
    result = self.db.session.execute(text(query), data)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 971, in _connection_for_bind
    engine, execution_options)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\orm\session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1138, in _do_get
    self._dec_overflow()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 1135, in _do_get
    return self._create_connection()
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\sqla
lchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Mikus\desktop\DojoAssignments\Python\virtualenv\Py27FlaskSQL\lib\site-packages\MySQ
Ldb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'user
s.users'")
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ ^C
(Py27FlaskSQL)
Mikus@DESKTOP-J7U7AKK MINGW64 ~/desktop/DojoAssignments/Python/SQL/users (master)
$ python server.py
[{u'first_name': u'Michael', u'last_name': u'Benson', u'created_at': datetime.datetime(2017, 4, 20,
16, 43, 12), u'updated_at': datetime.datetime(2017, 4, 20, 16, 43, 12), u'email': u'freefaller@gmail
.com', u'id': 1L}]
 * Restarting with stat
[{u'first_name': u'Michael', u'last_name': u'Benson', u'created_at': datetime.datetime(2017, 4, 20,
16, 43, 12), u'updated_at': datetime.datetime(2017, 4, 20, 16, 43, 12), u'email': u'freefaller@gmail
.com', u'id': 1L}]
 * Debugger is active!
 * Debugger PIN: 970-494-527
 * Running on http://127.0.0.1:3306/ (Press CTRL+C to quit)
